music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [

    # /music/
    url(r'^$' , views.IndexView.as_view() , name='index'),


    # /music/783/  or any number maybe
    url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name='detail'),

    # /music/783/favourite/
    url(r'^(?P<album_id>[0-9]+)/favourite/$' , views.favourite , name='favourite'),

    #/music/add_album/
    url(r'^add_album/$',views.AlbumCreate.as_view() ,name='album-add'),

    # /music/update_album/
    url(r'^update_album/$', views.ShowUpdate.as_view(), name='album-update'),

    #/music/update/id/
    url(r'^update_album/(?P<pk>[0-9]+)/$' , views.AlbumUpdate.as_view() , name='album-update-id'),

    # /music/delete_album/
    url(r'^delete_album/$', views.ShowUpdate.as_view(), name='album-delete'),

    # /music/delete/id/
    url(r'^delete_album/(?P<pk>[0-9]+)/$', views.AlbumDelete.as_view(), name='album-delete-id'),

    # /music/registration_form/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

]

thenewboston/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.conf.urls.static import static

class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(max_length=250)


    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.artist + "->" + self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=100)
    is_favourite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

music/views.py
from django.http import HttpResponse
from .models import Album, Song
from django.http import Http404
from django.template import loader
from django.shortcuts import render,get_object_or_404,redirect
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from . forms import UserForm
from django.views.generic import View

'''def index(request):
    all_albums = Album.objects.all()
   # template = loader.get_template('music/index.html')
    context = {
        'all_albums' : all_albums,
    }
    return render(request ,'music/index.html' , context )
  #  return HttpResponse(template.render(context , request))
'''
'''def detail(request, album_id):

  album = get_object_or_404( Album , id=album_id)
  template = loader.get_template('music/detail.html')
  context = {
      'album': album,
  }
  return HttpResponse(template.render(context , request)) '''
""" try :
    album = Album.objects.get(id=album_id)
    except :
    raise Http404(' ERROR 404 PAGE DOESNOT EXIST') """

class ShowUpdate(generic.ListView):
    template_name = 'music/album-update.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()



class IndexView(generic.ListView):

    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):

    model = Album
    template_name = 'music/detail.html'


def favourite(request,album_id):
    album = get_object_or_404( Album , id=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])

    except:
        return render(request, 'music/detail.html',{
            'album': album,
            'error_message': 'Invalid Choice - Please make a valid one'
        })

    selected_song.is_favourite = True
    selected_song.save()
    context = {
        'album': album,
    }
    return render(request,'music/detail.html',context)

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
   form_class = UserForm
   template_name = 'music/registration_form.html'

   def get(self,request):
       form = self.form_class(None)
       return render(request , self.template_name , {'form':form})

   def post(self,request):
       form = self.form_class(request.POST)

       if form.is_valid():
           user = form.save(commit=False)
           username = form.cleaned_data['username']
           password = form.cleaned_data['password']
           user.set_password(password)
           user.save()

           user = authenticate(username=username, password=password)

           if user is not None:
               login(request,user)
               return redirect('music:index')

       return render(request , self.template_name , {'form':form} )

music/templates/music/album-update.html
<h2> Here are all my albums </h2>
<ul>
    {% if all_albums %}

    {% for album in all_albums %}
            <li> <a href="{{ album.id }}/"> {{ album.album_title }} </a></li>
    {% endfor %}

    {% else %}
        <h3> Album section is empty </h3>
{% endif %}

music/templates/music/album_form.html
<h2><em>Add some stuff-|-></em></h2>
<form action="" method="post">
{% csrf_token %}
{% for field in form %}
    {{  field.label_tag }} <br/>
    {{  field }}
    <br/>
    <hr />

{% endfor %}

<button type="submit">Submit</button>
</form>

music/templates/music/detail.html
<img src="{{album.album_logo.url}} " width="500" height="500" />
<h1> {{ album.album_title }} </h1>
<h2> {{ album.artist }} </h2>

  <form action = "{% url 'music:favourite' album.id %}" method="post">
       {% csrf_token %}
      <p><strong><em> Tickmark your favourite song </em></strong></p>
      {% for song in album.song_set.all %}
          <input type="radio" name="song" value="{{ song.id }}" id="song{{forloop.counter}}" />

          <label for="song{{forloop.counter}}">
          {{ song.song_title }}
          {% if song.is_favourite %}
           **
          {% endif %}
          </label>
          <br/>
      {% endfor %}
      <input type="submit"  value="favourite"/>
        <br />
        {% if error_message %}
       <h3> {{ error_message }} </h3>
      {% endif %}
  </form>

music/templates/music/index.html
<h2> Here are all my albums </h2>

<ul>
    {% if all_albums %}

    {% for album in all_albums %}
            <li> <a href="{{ album.id }}/"> {{ album.album_title }} </a></li>
    {% endfor %}

    {% else %}
        <h3> Album section is empty </h3>
{% endif %}

</ul>
<hr />
<br/>
<li><a href=" /music/add_album/"> Add-album </a></li>
<li><a href=" /music/update_album/"> Update-album  </a></li>
<li><a href=" /music/delete_album/"> Delete-album  </a></li>

music/templates/music/registration_form.html
<h2><em>---Sign in---</em></h2>
<form action="" method="post">
{% csrf_token %}
{% for field in form %}
    {{  field.label_tag }} <br/>
    {{  field }}
    <br/>
    <hr />

{% endfor %}

<button type="submit">Submit</button>
</form>